const assert=require('node:assert/strict');
const {chromium}=require('C:/Users/wizar/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const api=require('./focus-next-games');
(async()=>{const browser=await chromium.launch();const errors=[];
async function create(level=2){const p=await browser.newPage({viewport:{width:320,height:844}});p.on('pageerror',e=>errors.push(e.message));await p.clock.install();await p.clock.pauseAt(new Date());await p.route('https://res.wx.qq.com/**',r=>r.fulfill({body:'window.results=[];window.wx={miniProgram:{postMessage(m){window.results.push(m.data)}}};'}));await p.goto('http://127.0.0.1:8080/focus.html?game=stroop_dimension&miniprogram=1&v=local28');await p.locator('#level-select').evaluate((s,l)=>{s.value=l;s.dispatchEvent(new Event('change'));},String(level));return p;}
async function value(p){const word=await p.locator('.next-color-word').innerText();const ink=await p.locator('.next-color-word').evaluate(n=>n.style.color);return (await p.locator('.next-rule').innerText()).includes('文字')?api.colors.findIndex(c=>c.name===word):api.colors.findIndex(c=>'rgb('+[0,2,4].map(i=>parseInt(c.hex.slice(1+i,3+i),16)).join(', ')+')'===ink);}
async function click(p,wrong=false){const a=await value(p);await p.locator(`[data-choice="${wrong?(a+1)%2:a}"]`).click();}
try{
const p=await create();await p.clock.runFor(60000);assert.match(await p.locator('#timer-badge').innerText(),/15.0/);assert.equal(await p.locator('.heart.active').count(),3);assert.equal(await p.locator('#timer-badge').isVisible(),true);
await p.getByRole('button',{name:'继续',exact:true}).click();await p.clock.runFor(1000);assert.match(await p.locator('#timer-badge').innerText(),/14.0/);await click(p);assert.match(await p.locator('#next-progress').innerText(),/1\/10/);await p.clock.runFor(350);await click(p,true);assert.equal(await p.locator('.heart.active').count(),2);assert.match(await p.locator('#next-progress').innerText(),/0\/10/);await p.clock.runFor(2000);assert.match(await p.locator('#timer-badge').innerText(),/15.0/);await p.clock.runFor(15000);assert.equal(await p.locator('.heart.active').count(),1);await p.clock.runFor(2000);await p.clock.runFor(15000);assert.equal(await p.locator('#report-modal').isVisible(),true);assert.equal(await p.evaluate(()=>window.results.length),1);await p.clock.runFor(60000);assert.equal(await p.evaluate(()=>window.results.length),1);await p.close();
const transition=await create();await transition.getByRole('button',{name:'继续',exact:true}).click();await transition.clock.runFor(14750);await click(transition);await transition.clock.runFor(300);assert.equal(await transition.locator('.heart.active').count(),2);assert.equal(await transition.locator('.next-error').isVisible(),true);await transition.close();
const complete=await create();await complete.getByRole('button',{name:'继续',exact:true}).click();for(let i=0;i<9;i++){await click(complete);await complete.clock.runFor(350);}await complete.clock.runFor(11700);await click(complete);assert.match(await complete.locator('#next-progress').innerText(),/10\/10/);await complete.clock.runFor(1200);assert.equal(await complete.getByRole('button',{name:'继续',exact:true}).count(),1);assert.match(await complete.locator('#timer-badge').innerText(),/20.0/);assert.equal(await complete.locator('.heart.active').count(),3);await complete.clock.runFor(60000);assert.equal(await complete.locator('.heart.active').count(),3);await complete.close();
const leave=await create();await leave.getByRole('button',{name:'继续',exact:true}).click();await leave.locator('#game-select').evaluate(s=>{s.value='simon_reverse';s.dispatchEvent(new Event('change'));});await leave.clock.runFor(60000);assert.equal(await leave.locator('.heart.active').count(),3);assert.equal(await leave.locator('#timer-badge').isVisible(),false);await leave.close();assert.deepEqual(errors,[]);
console.log('Stroop level timer: ready state, progress, reset, third-error report, transition timeout, last-second completion and timer cleanup passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
