const assert = require('node:assert/strict');
const {chromium}=require('C:/Users/wizar/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('node:fs');
let browser;
(async()=>{
 browser=await chromium.launch(); const errors=[];
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://res.wx.qq.com/**',r=>r.fulfill({body:''}));
 await page.goto('http://127.0.0.1:8080/index.html?tab=focus');
 const frame=page.frameLocator('.focus-frame');await frame.locator('#focus-catalog a').first().waitFor();
 await frame.getByRole('button',{name:'English',exact:true}).click();
 assert.equal(await frame.locator('html').getAttribute('lang'),'en');
 assert.equal(await frame.locator('#focus-home h1').innerText(),'Choose today’s training');
 assert.equal(await frame.locator('#focus-catalog a').count(),20);
 assert.equal(await frame.locator('#home-history h2').innerText(),'Today’s training');
 await page.reload();await frame.locator('#focus-catalog a').first().waitFor();
 assert.equal(await frame.locator('html').getAttribute('lang'),'en');
 await frame.locator('#home-history select').selectOption('bimodal_divert');
 await frame.getByRole('button',{name:'中文',exact:true}).click();
 assert.match(await frame.locator('#home-history svg').getAttribute('aria-label'), /视听双通道分流/);
 assert.equal(await frame.locator('#focus-home h1').innerText(),'选择今天的训练');
 await frame.getByRole('button',{name:'English',exact:true}).click();
 await page.goto('http://127.0.0.1:8080/focus.html?v=local27');
 await page.clock.install();await page.clock.pauseAt(new Date());
 let findings={};
 async function scan(label){findings[label]=await page.evaluate(()=>{const found=[];const walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode()){if(/[\u4e00-\u9fff]/.test(n.nodeValue)&&!n.parentElement.closest('script,style,[translate="no"]')&&n.parentElement.getBoundingClientRect().width&&n.parentElement.getBoundingClientRect().height)found.push(n.nodeValue.trim());}return [...new Set(found)];});}
 await scan('home');
 const ids=await page.locator('#focus-catalog a').evaluateAll(nodes=>nodes.map(n=>n.hash.slice(1)));
 for(const id of ids){await page.locator('#game-select').evaluate((s,v)=>{s.value=v;s.dispatchEvent(new Event('change'));},id);await page.locator('#level-select').evaluate((s,id)=>{s.value=id==='nback_flow'?'12':id==='matrix_flash'?'15':id==='ufov_dual_field'?'14':'10';s.dispatchEvent(new Event('change'));},id);await scan(id+'-ready');const button=page.locator('#game-controls button:enabled').first();if(await button.count())await button.click();await scan(id+'-playing');await page.clock.runFor(1000);await scan(id+'-after1s');await page.clock.runFor(7000);await scan(id+'-later');}
 await page.locator('#btn-test-fail').click();await scan('report');
 fs.writeFileSync('scratch/focus-language-audit.json',JSON.stringify(findings,null,2));console.log('Untranslated interface text:',JSON.stringify(Object.fromEntries(Object.entries(findings).filter(([,v])=>v.length))));
 assert.deepEqual(Object.entries(findings).filter(([,values])=>values.length), [], 'All visible interface text should be translated');
 await page.locator('#game-select').evaluate(s=>{s.value='bimodal_divert';s.dispatchEvent(new Event('change'));});
 await page.getByRole('button',{name:'Start level 1',exact:true}).click();
 assert.equal(await page.locator('.bimodal-countdown').innerText(),'3');
 const records = await page.evaluate(()=>localStorage.getItem('focus_training_records_v1'));
 await page.getByRole('button',{name:'中文',exact:true}).click();
 assert.equal(await page.locator('.bimodal-countdown').innerText(),'3');
 await page.clock.runFor(1000);
 assert.equal(await page.locator('.bimodal-countdown').innerText(),'2');
 await page.getByRole('button',{name:'English',exact:true}).click();
 assert.equal(await page.locator('.bimodal-countdown').innerText(),'2');
 assert.equal(await page.locator('.heart.active').count(),3);
 assert.equal(await page.evaluate(()=>localStorage.getItem('focus_training_records_v1')),records);
 await page.locator('#game-select').evaluate(s=>{s.value='semantic_synthesis';s.dispatchEvent(new Event('change'));});
 await page.getByRole('button',{name:'Start level 1',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Text practice',exact:true}).count(),0);
 const categories = await page.locator('.semantic-category-row [translate="no"]').allTextContents();
 assert(categories.length && categories.every(word=>/[\u4e00-\u9fff]/.test(word)), 'Training categories must remain Chinese');
 await page.getByRole('button',{name:'中文',exact:true}).click();
 assert.deepEqual(await page.locator('.semantic-category-row [translate="no"]').allTextContents(),categories);
 await page.getByRole('button',{name:'English',exact:true}).click();
 assert.deepEqual(await page.locator('.semantic-category-row [translate="no"]').allTextContents(),categories);
 await page.locator('#game-select').evaluate(s=>{s.value='stroop_dimension';s.dispatchEvent(new Event('change'));});
 await page.getByRole('button',{name:'Start level 1',exact:true}).click();
 assert.match(await page.locator('.next-color-word').innerText(),/[\u4e00-\u9fff]/);
 assert.match(await page.locator('.next-choice').first().innerText(),/[\u4e00-\u9fff]/);
 console.log('Focus tab language controls, persistence, 20 games, reports, in-progress switching and preserved Chinese stimuli passed');
 assert.deepEqual(errors,[]);
 await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
